{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customDebugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/engine\/networkerror\/customdebugdescription"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Engine\/documentation\/Engine\/NetworkError\/customDebugDescription","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Mapped to NSDebugDescriptionErrorKey. Suitable for debugging."}],"kind":"symbol","metadata":{"role":"symbol","title":"customDebugDescription","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customDebugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"s:6Engine12NetworkErrorO22customDebugDescriptionSSvp","extendedModule":"Engine","modules":[{"name":"Engine"}]},"hierarchy":{"paths":[["doc:\/\/Engine\/documentation\/Engine","doc:\/\/Engine\/documentation\/Engine\/NetworkError","doc:\/\/Engine\/documentation\/Engine\/NetworkError\/LoggableError-Implementations"]]},"references":{"doc://Engine/documentation/Engine/NetworkError/LoggableError-Implementations":{"role":"collectionGroup","title":"LoggableError Implementations","abstract":[],"identifier":"doc:\/\/Engine\/documentation\/Engine\/NetworkError\/LoggableError-Implementations","kind":"article","type":"topic","url":"\/documentation\/engine\/networkerror\/loggableerror-implementations"},"doc://Engine/documentation/Engine/NetworkError":{"role":"symbol","title":"NetworkError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkError"}],"abstract":[],"identifier":"doc:\/\/Engine\/documentation\/Engine\/NetworkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/engine\/networkerror"},"doc://Engine/documentation/Engine":{"role":"collection","title":"Engine","abstract":[],"identifier":"doc:\/\/Engine\/documentation\/Engine","kind":"symbol","type":"topic","url":"\/documentation\/engine"},"doc://Engine/documentation/Engine/NetworkError/customDebugDescription":{"role":"symbol","title":"customDebugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customDebugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Mapped to NSDebugDescriptionErrorKey. Suitable for debugging."}],"identifier":"doc:\/\/Engine\/documentation\/Engine\/NetworkError\/customDebugDescription","kind":"symbol","type":"topic","url":"\/documentation\/engine\/networkerror\/customdebugdescription"}}}